/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chartadvancedpie;

import shuntingyard.ExpressionParser;


/**
 * This is a utility class that uses factory methods to set everything up.
 * Compiler generated by the factory method prepareCompiler is then ready to use
 * functions, declared by modifying the constructor of ExtendedFunctionTokenFactory.
 * @author thegoodhen
 */
public class InterpreterFacade {

	public static GUICompiler prepareCompiler(GUIPanel gp)
	{
		GUICompiler gc=new GUICompiler(gp);
		DotNotationParser ep=new DotNotationParser();
		ep.setFactory(new ImprovedGeneralTokenFactory());
		gc.setExpressionParser(ep);
		return gc;
		
	}
	
}
